[versions]
apache-poi = "5.2.3"
clikt = "5.0.3"

[libraries]
poi = { group = "org.apache.poi", name = "poi", version.ref = "apache-poi" }
poi-ooxml = { group = "org.apache.poi", name = "poi-ooxml", version.ref = "apache-poi" }
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version.ref = "clikt" }
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.9.0" }

[bundles]
poi = ["poi", "poi-ooxml"]
